export const dadosPessoaisActions = (state) =>({ type: 'NOME', state })
export const dadosPessoaisActions = (state) =>({ type: 'EMAIL', state })
export const dadosPessoaisActions = (state) =>({ type: 'CPF', state })
export const dadosPessoaisActions = (state) =>({ type: 'ENDEREÇO', state })
export const dadosPessoaisActions = (state) =>({ type: 'CIDADE', state })
export const dadosPessoaisActions = (state) =>({ type: 'ESTADO', state })
export const dadosPessoaisActions = (state) =>({ type: 'TIPO', state })